import { useEffect, useRef, useState } from 'react';
import { MotionValue } from 'framer-motion';
import { useUserStore } from '../../store/userStore';


export const DISCLAIMER_TEXT = `About The Game
At Your Age (AYA) is an interactive personality discovery game designed for entertainment and personal reflection 
purposes only. The scenarios, stories and personality assessments presented in this app are fictional simulations 
inspired by publicly available historical information and are not intended to be factually comprehensive or 
academically verified.
  
About Personality Assessments
The personality profiles, DNA reports, trait scores, Future Self predictions and archetype matches generated by AYA 
are based on in-game decisions and quiz responses. They are designed for entertainment and self-reflection only. They 
do not constitute professional psychological assessments, career advice, mental health evaluations or any form of 
clinical diagnosis. Results should not be used as the basis for any major life decisions.
  
About Real People
AYA features fictional game scenarios inspired by the lives of real public figures. These scenarios are creative 
interpretations and simulations — they do not claim to accurately represent the actual thoughts, decisions, beliefs 
or private lives of any individual. All dialogue and choices presented are fictional. Resemblance to actual events is 
used for inspirational and educational purposes only.
  
About User Data
AYA collects basic user information including name, age and mobile number to personalize your experience. We collect 
behavioral data including quiz responses, in-game choices and session data to improve our recommendations. We do not 
sell individual personal data to third parties. Aggregated and anonymized insights may be used for research and 
product improvement. By using AYA you consent to the collection and use of this data as described in our Privacy 
Policy.
  
About Push Notifications
If you enable push notifications AYA may send you daily reminders and motivational messages. You can disable 
notifications at any time through your device settings.
  
Age Requirement
AYA is designed for users aged 13 and above. Users under 18 should use this app with parental awareness. We do not 
knowingly collect personal information from children under 13.
  
Mental Health Notice
Some story scenarios may touch on themes including failure, rejection, loss, loneliness and emotional struggle. 
These are presented in an educational and motivational context. If you are experiencing mental health difficulties 
please seek support from a qualified professional.
  
No Guarantees
AYA makes no guarantees about the accuracy of personality assessments, future self predictions or archetype matches. 
These features are designed to inspire reflection and curiosity — not to predict your actual future.
  
Contact
For questions or concerns about this disclaimer or your data please contact us at: atyourage@gmail.com
Last updated: April 2026`;

interface AntiGravityCanvasProps {
    progress: MotionValue<number>;
    onReady: () => void;
}

export function AntiGravityCanvas({ progress, onReady }: AntiGravityCanvasProps) {
    const isCandyMode = useUserStore((state) => state.isCandyMode);
    const setIntroVideoCompleted = useUserStore((state) => state.setIntroVideoCompleted);
    // Use the MP4s generated from the frames for memory caching
    const videoUrl = isCandyMode ? '/assets/map_frames.mp4' : '/assets/map_frames_dark.mp4';

    const videoRef = useRef<HTMLVideoElement>(null);
    const [isReady, setIsReady] = useState(false);


    useEffect(() => {
        setIntroVideoCompleted(false);
        setIsReady(false);
        
        const video = videoRef.current;
        if (!video) return;

        const handleCanPlay = () => {
            if (!isReady) {
                setIsReady(true);
                setIntroVideoCompleted(true);
                if (onReady) onReady();
            }
        };

        // We use native video buffering instead of manual Blob fetching.
        // It's much faster for the user to enter the map while it progressively buffers.
        video.addEventListener('canplaythrough', handleCanPlay);
        video.addEventListener('loadeddata', handleCanPlay);

        // Pre-fetch/buffer the video natively
        video.load();

        return () => {
            video.removeEventListener('canplaythrough', handleCanPlay);
            video.removeEventListener('loadeddata', handleCanPlay);
        };
    }, [videoUrl, isReady, onReady, setIntroVideoCompleted]);

    useEffect(() => {
        const unsubscribe = progress.on('change', (latest: number) => {
            const video = videoRef.current;
            if (video && video.duration && !isNaN(video.duration)) {
                // Constrain progress between 0 and 1
                const currentProgress = Math.max(0, Math.min(1, latest));
                const targetTime = currentProgress * video.duration;
                
                // Update time if it differs to avoid unnecessary DOM writes
                // A very small threshold to avoid spamming the DOM for micro-pixels,
                // but low enough to avoid stuttering on scroll.
                if (Math.abs(video.currentTime - targetTime) > 0.001) {
                    video.currentTime = targetTime;
                }
            }
        });
        
        return () => unsubscribe();
    }, [progress]);

    return (
        <>
            <div className={`fixed top-0 left-0 w-full h-full pointer-events-none z-0 overflow-hidden bg-slate-900 transition-opacity duration-1000 ${isReady ? 'opacity-100' : 'opacity-0'}`}>
                <video
                    ref={videoRef}
                    src={videoUrl}
                    className="w-full h-full object-cover opacity-80"
                    style={{ filter: isCandyMode ? 'contrast(1.1) brightness(1.1)' : 'contrast(1.2)' }}
                    muted
                    playsInline
                    preload="auto"
                />
            </div>
        </>
    );
}
