import { useEffect, useRef, useState } from 'react';
import { MotionValue } from 'framer-motion';
import { useUserStore } from '../../store/userStore';
import { createPortal } from 'react-dom';

export const DISCLAIMER_TEXT = `About The Game
At Your Age (AYA) is an interactive personality discovery game designed for entertainment and personal reflection 
purposes only. The scenarios, stories and personality assessments presented in this app are fictional simulations 
inspired by publicly available historical information and are not intended to be factually comprehensive or 
academically verified.
  
About Personality Assessments
The personality profiles, DNA reports, trait scores, Future Self predictions and archetype matches generated by AYA 
are based on in-game decisions and quiz responses. They are designed for entertainment and self-reflection only. They 
do not constitute professional psychological assessments, career advice, mental health evaluations or any form of 
clinical diagnosis. Results should not be used as the basis for any major life decisions.
  
About Real People
AYA features fictional game scenarios inspired by the lives of real public figures. These scenarios are creative 
interpretations and simulations — they do not claim to accurately represent the actual thoughts, decisions, beliefs 
or private lives of any individual. All dialogue and choices presented are fictional. Resemblance to actual events is 
used for inspirational and educational purposes only.
  
About User Data
AYA collects basic user information including name, age and mobile number to personalize your experience. We collect 
behavioral data including quiz responses, in-game choices and session data to improve our recommendations. We do not 
sell individual personal data to third parties. Aggregated and anonymized insights may be used for research and 
product improvement. By using AYA you consent to the collection and use of this data as described in our Privacy 
Policy.
  
About Push Notifications
If you enable push notifications AYA may send you daily reminders and motivational messages. You can disable 
notifications at any time through your device settings.
  
Age Requirement
AYA is designed for users aged 13 and above. Users under 18 should use this app with parental awareness. We do not 
knowingly collect personal information from children under 13.
  
Mental Health Notice
Some story scenarios may touch on themes including failure, rejection, loss, loneliness and emotional struggle. 
These are presented in an educational and motivational context. If you are experiencing mental health difficulties 
please seek support from a qualified professional.
  
No Guarantees
AYA makes no guarantees about the accuracy of personality assessments, future self predictions or archetype matches. 
These features are designed to inspire reflection and curiosity — not to predict your actual future.
  
Contact
For questions or concerns about this disclaimer or your data please contact us at: atyourage@gmail.com
Last updated: April 2026`;

// Global cache to prevent re-fetching the 30MB video every time the map remounts (fixes flickering/repeated loading)
const globalVideoBlobCache: Record<string, string> = {};
const globalVideoFetchPromises: Record<string, Promise<string>> = {};

interface AntiGravityCanvasProps {
    progress: MotionValue<number>;
    onReady: () => void;
}

export function AntiGravityCanvas({ progress, onReady }: AntiGravityCanvasProps) {
    const isCandyMode = useUserStore((state) => state.isCandyMode);
    const setIntroVideoCompleted = useUserStore((state) => state.setIntroVideoCompleted);
    // Use the MP4s generated from the frames for memory caching
    const videoUrl = isCandyMode ? '/assets/map_frames.mp4' : '/assets/map_frames_dark.mp4';

    const videoRef = useRef<HTMLVideoElement>(null);
    const [isReady, setIsReady] = useState(false);
    const [loadingProgress, setLoadingProgress] = useState(0);


    useEffect(() => {
        setIntroVideoCompleted(false);
        setIsReady(false);
        setLoadingProgress(0);
        
        const video = videoRef.current;
        if (!video) return;

        let isCancelled = false;

        const handleCanPlay = () => {
            if (!isReady && !isCancelled) {
                setIsReady(true);
                setIntroVideoCompleted(true);
                // Defer pause to ensure iOS Safari paints the first frame
                requestAnimationFrame(() => {
                    requestAnimationFrame(() => {
                        if (video && !isCancelled) video.pause();
                    });
                });
                if (onReady) onReady();
            }
        };

        const setupVideoSource = async () => {
            // If already cached globally, skip the loading screen entirely!
            if (globalVideoBlobCache[videoUrl]) {
                setLoadingProgress(100);
                video.src = globalVideoBlobCache[videoUrl];
                video.load();
                return;
            }

            try {
                // Fetch video into a Blob to cache in memory and guarantee lag-free scrubbing (fixes mobile scrolling lag)
                if (!globalVideoFetchPromises[videoUrl]) {
                    globalVideoFetchPromises[videoUrl] = new Promise(async (resolve, reject) => {
                        try {
                            const response = await fetch(videoUrl);
                            if (!response.body) throw new Error('No body');
                            
                            const reader = response.body.getReader();
                            const contentLength = +(response.headers.get('Content-Length') || (isCandyMode ? '7000000' : '33000000'));
                            let receivedLength = 0;
                            const chunks = [];
                            
                            while(true) {
                                const {done, value} = await reader.read();
                                if (done) break;
                                
                                chunks.push(value);
                                receivedLength += value.length;
                                // Update progress only if it's the current active fetch
                                if (!isCancelled) {
                                    setLoadingProgress(Math.min(100, Math.round((receivedLength / contentLength) * 100)));
                                }
                            }
                            
                            const blob = new Blob(chunks, { type: 'video/mp4' });
                            const blobUrl = URL.createObjectURL(blob);
                            globalVideoBlobCache[videoUrl] = blobUrl;
                            resolve(blobUrl);
                        } catch (err) {
                            reject(err);
                        }
                    });
                }

                // Wait for the active fetch (whether started by us or a previous mount)
                const finalBlobUrl = await globalVideoFetchPromises[videoUrl];
                
                if (!isCancelled) {
                    video.src = finalBlobUrl;
                    video.load();
                }
            } catch (err) {
                console.error("Failed to fetch video into memory cache:", err);
                // Fallback directly to URL if fetch fails
                if (!isCancelled) {
                    video.src = videoUrl;
                    video.load();
                }
            }
        };

        setupVideoSource();

        video.addEventListener('canplaythrough', handleCanPlay);
        video.addEventListener('loadeddata', handleCanPlay);

        return () => {
            isCancelled = true;
            video.removeEventListener('canplaythrough', handleCanPlay);
            video.removeEventListener('loadeddata', handleCanPlay);
        };
    }, [videoUrl, onReady, setIntroVideoCompleted, isReady, isCandyMode]);

    useEffect(() => {
        const unsubscribe = progress.on('change', (latest: number) => {
            const video = videoRef.current;
            if (video && video.duration && !isNaN(video.duration)) {
                // Constrain progress between 0 and 1
                const currentProgress = Math.max(0, Math.min(1, latest));
                const targetTime = currentProgress * video.duration;
                
                // Update time if it differs to avoid unnecessary DOM writes
                // A very small threshold to avoid spamming the DOM for micro-pixels,
                // but low enough to avoid stuttering on scroll.
                if (Math.abs(video.currentTime - targetTime) > 0.001) {
                    video.currentTime = targetTime;
                }
            }
        });
        
        return () => unsubscribe();
    }, [progress]);

    return (
        <>
            {!isReady && createPortal(
                <div className="fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-[#050814]">
                    <div className="absolute bottom-1/2 translate-y-1/2 flex flex-col items-center text-cyan-400 font-mono tracking-widest font-bold z-10 w-64 max-w-[80%]">
                        <div className="text-sm mb-4 animate-pulse">CACHING TIMELINE...</div>
                        <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden shadow-[0_0_15px_rgba(0,241,254,0.3)]">
                            <div
                                className="h-full bg-cyan-400 transition-all duration-200"
                                style={{ width: `${loadingProgress}%` }}
                            />
                        </div>
                    </div>
                </div>,
                document.body
            )}
            <div className={`fixed top-0 left-0 w-full h-full pointer-events-none z-0 overflow-hidden bg-slate-900 transition-opacity duration-1000 ${isReady ? 'opacity-100' : 'opacity-0'}`}>
                <video
                    ref={videoRef}
                    className="w-full h-full object-cover opacity-80"
                    style={{ filter: isCandyMode ? 'contrast(1.1) brightness(1.1)' : 'contrast(1.2)' }}
                    muted
                    playsInline
                    autoPlay
                    preload="auto"
                />
            </div>
        </>
    );
}
