import { useEffect, useRef, useState } from 'react';
import { MotionValue } from 'framer-motion';
import { useUserStore } from '../../store/userStore';
import { createPortal } from 'react-dom';

export const DISCLAIMER_TEXT = `About The Game
At Your Age (AYA) is an interactive personality discovery game designed for entertainment and personal reflection 
purposes only. The scenarios, stories and personality assessments presented in this app are fictional simulations 
inspired by publicly available historical information and are not intended to be factually comprehensive or 
academically verified.
  
About Personality Assessments
The personality profiles, DNA reports, trait scores, Future Self predictions and archetype matches generated by AYA 
are based on in-game decisions and quiz responses. They are designed for entertainment and self-reflection only. They 
do not constitute professional psychological assessments, career advice, mental health evaluations or any form of 
clinical diagnosis. Results should not be used as the basis for any major life decisions.
  
About Real People
AYA features fictional game scenarios inspired by the lives of real public figures. These scenarios are creative 
interpretations and simulations — they do not claim to accurately represent the actual thoughts, decisions, beliefs 
or private lives of any individual. All dialogue and choices presented are fictional. Resemblance to actual events is 
used for inspirational and educational purposes only.
  
About User Data
AYA collects basic user information including name, age and mobile number to personalize your experience. We collect 
behavioral data including quiz responses, in-game choices and session data to improve our recommendations. We do not 
sell individual personal data to third parties. Aggregated and anonymized insights may be used for research and 
product improvement. By using AYA you consent to the collection and use of this data as described in our Privacy 
Policy.
  
About Push Notifications
If you enable push notifications AYA may send you daily reminders and motivational messages. You can disable 
notifications at any time through your device settings.
  
Age Requirement
AYA is designed for users aged 13 and above. Users under 18 should use this app with parental awareness. We do not 
knowingly collect personal information from children under 13.
  
Mental Health Notice
Some story scenarios may touch on themes including failure, rejection, loss, loneliness and emotional struggle. 
These are presented in an educational and motivational context. If you are experiencing mental health difficulties 
please seek support from a qualified professional.
  
No Guarantees
AYA makes no guarantees about the accuracy of personality assessments, future self predictions or archetype matches. 
These features are designed to inspire reflection and curiosity — not to predict your actual future.
  
Contact
For questions or concerns about this disclaimer or your data please contact us at: atyourage@gmail.com
Last updated: April 2026`;

interface AntiGravityCanvasProps {
    progress: MotionValue<number>;
    onReady: () => void;
}

export function AntiGravityCanvas({ progress, onReady }: AntiGravityCanvasProps) {
    const isCandyMode = useUserStore((state) => state.isCandyMode);
    const setIntroVideoCompleted = useUserStore((state) => state.setIntroVideoCompleted);
    // Use the MP4s generated from the frames for memory caching
    const videoUrl = isCandyMode ? '/assets/map_frames.mp4' : '/assets/map_frames_dark.mp4';

    const videoRef = useRef<HTMLVideoElement>(null);
    const [isReady, setIsReady] = useState(false);
    const [loadingProgress, setLoadingProgress] = useState(0);

    useEffect(() => {
        setIntroVideoCompleted(false);
        setIsReady(false);
        setLoadingProgress(0);

        const video = videoRef.current;
        if (!video) return;

        let blobUrl = '';
        let isCancelled = false;

        // Fetch video into a Blob to cache in memory and guarantee lag-free scrubbing
        const fetchVideo = async () => {
            try {
                const response = await fetch(videoUrl);
                if (!response.body) throw new Error('No body');
                
                const reader = response.body.getReader();
                const contentLength = +(response.headers.get('Content-Length') || '14000000'); // Approx 14MB fallback
                let receivedLength = 0;
                const chunks = [];
                
                while(true) {
                    const {done, value} = await reader.read();
                    if (done) break;
                    
                    chunks.push(value);
                    receivedLength += value.length;
                    if (!isCancelled) {
                        setLoadingProgress(Math.min(100, Math.round((receivedLength / contentLength) * 100)));
                    }
                }
                
                if (isCancelled) return;

                const blob = new Blob(chunks, { type: 'video/mp4' });
                blobUrl = URL.createObjectURL(blob);
                
                video.src = blobUrl;
                video.load();
                
            } catch (err) {
                console.error("Failed to fetch video into memory cache:", err);
                // Fallback directly to URL if fetch fails
                if (!isCancelled) {
                    video.src = videoUrl;
                    video.load();
                }
            }
        };

        fetchVideo();

        const handleCanPlayThrough = () => {
            if (isCancelled) return;
            // Prevent duplicate triggers
            if (video.readyState >= 3) {
                setIsReady(true);
                setIntroVideoCompleted(true);
                onReady();
            }
        };

        video.addEventListener('canplaythrough', handleCanPlayThrough);
        video.addEventListener('loadeddata', handleCanPlayThrough);

        return () => {
            isCancelled = true;
            video.removeEventListener('canplaythrough', handleCanPlayThrough);
            video.removeEventListener('loadeddata', handleCanPlayThrough);
            if (blobUrl) {
                URL.revokeObjectURL(blobUrl);
            }
        };
    }, [videoUrl, onReady, setIntroVideoCompleted]);

    useEffect(() => {
        const video = videoRef.current;
        if (!video || !isReady) return;

        let animationFrameId: number;
        
        const tick = () => {
            if (video.duration) {
                const currentProgress = Math.max(0, Math.min(1, progress.get() || 0));
                const targetTime = currentProgress * video.duration;
                // Update precisely without arbitrary threshold
                if (video.currentTime !== targetTime) {
                    video.currentTime = targetTime;
                }
            }
            animationFrameId = requestAnimationFrame(tick);
        };

        tick();

        return () => {
            cancelAnimationFrame(animationFrameId);
        };
    }, [isReady, progress]);

    return (
        <>
            {!isReady && createPortal(
                <div className="fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-[#050814]">
                    <div className="absolute bottom-1/2 translate-y-1/2 flex flex-col items-center text-cyan-400 font-mono tracking-widest font-bold z-10 w-64 max-w-[80%]">
                        <div className="text-sm mb-4 animate-pulse">CACHING TIMELINE...</div>
                        <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden shadow-[0_0_15px_rgba(0,241,254,0.3)]">
                            <div
                                className="h-full bg-cyan-400 transition-all duration-200"
                                style={{ width: `${loadingProgress}%` }}
                            />
                        </div>
                    </div>
                </div>,
                document.body
            )}
            <div className="fixed top-0 left-0 w-full h-full pointer-events-none z-0 overflow-hidden bg-slate-900">
                <video
                    ref={videoRef}
                    className="w-full h-full object-cover"
                    muted
                    playsInline
                    preload="auto"
                />
            </div>
        </>
    );
}
